# Generated by Django 3.0.2 on 2020-02-01 14:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPI', '0002_auto_20200201_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='GeoLocation',
        ),
        migrations.AddField(
            model_name='event',
            name='Location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
