# Generated by Django 3.0.2 on 2020-02-01 14:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPI', '0003_auto_20200201_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
