# Generated by Django 3.0.2 on 2020-02-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPI', '0005_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventType',
            field=models.CharField(choices=[('C', 'CONSTRUCTION'), ('S', 'SPECIAL_EVENT'), ('I', 'INCIDENT'), ('W', 'WEATHER_CONDITION'), ('W', 'ROAD_CONDITION')], max_length=20),
        ),
    ]
