# Generated by Django 3.0.2 on 2020-02-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPI', '0006_auto_20200206_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventType',
            field=models.CharField(choices=[('CONSTRUCTION', 'CONSTRUCTION'), ('SPECIAL_EVENT', 'SPECIAL_EVENT'), ('INCIDENT', 'INCIDENT'), ('WEATHER_CONDITION', 'WEATHER_CONDITION'), ('ROAD_CONDITION', 'ROAD_CONDITION')], max_length=20, verbose_name='EVENT_TYPE'),
        ),
    ]
